name: Build-Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  packages: write

env:
  BUILD_ENVIRONMENT: GitHub
  
jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up cache for build
        uses: actions/cache@v3
        with:
          path: mywebapp/**
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: "8.0.x"

      - name: Configure NuGet credentials
        run: |
          sed -i 's/MyName/${{ github.actor }}/g' nuget.config
          sed -i 's/MyPAT/${{ secrets.GITHUB_TOKEN }}/g' nuget.config

      - name: Restore dependencies
        run: dotnet restore "${{github.workspace}}/my-web-app.sln" --verbosity detailed

      - name: Build
        run: dotnet build "${{github.workspace}}/my-web-app.sln"  --no-restore --configuration Release

      - name: Test
        run: dotnet test "${{github.workspace}}/my-web-app.sln" --no-restore --logger:"junit;LogFilePath=${{ github.workspace }}/Testresults/test-results.xml"

      # create a test summary markdown file
      # if you don't specify an output file, it will automatically add
      # as a job summary. If you specify an output file, you have to
      # create your own step of adding it to the job summary. I am
      # intentionally doing that to show job summaries
      - name: Create test summary
        uses: test-summary/action@v2.4
        with:
          paths: ${{ github.workspace }}/Testresults/*.xml
          output: ${{ github.workspace }}/Testresults/summary.md
          show: "all"
        if: always()

      # I am adding the test results to the Job Summary
      - name: Add Test Results To Job Summary
        run: |
          echo "TEST RESULTS:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          cat "${{ github.workspace }}/Testresults/summary.md" >> $GITHUB_STEP_SUMMARY
        if: always()

        
      - name: Save build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: mywebapp/**

        
  pause-for-approval:
    needs: build
    runs-on: windows-2019

    steps:
        - name: Install jq
          run: sudo apt-get update && sudo apt-get install -y jq
    
        - name: Checking for Merge
          run: |
            PULL_REQUEST_NUMBER=${{github.event.number}}
            OWNER=${{github.actor}}
            REPO=${{github.event.repository.name}}
            TOKEN=${{secrets.GITHUB_TOKEN}}
            while true; do
              STATUS=$(curl -H "Authorization: token $TOKEN" \
                            -H "Accept: application/vnd.github.v3+json" \
                            https://api.github.com/repos/$OWNER/$REPO/pulls/$PULL_REQUEST_NUMBER | jq -r .merged)
              if [[ $STATUS == "true" ]]; then
                echo "Pull request is merged. Continuing workflow..."
                break
              else
                echo "Pull request not yet merged. Waiting..."
                sleep 60 # Wait 60 seconds before checking again
              fi
            done

  
  Publish:
    needs: build
    runs-on: windows-2019
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore cache for build
        uses: actions/cache@v3
        with:
          path: mywebapp/**
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          
      - name: Save build artifact
        uses: actions/upload-artifact@v4
        with:
          name: "${{github.event.repository.name}}-DEV"
          path: mywebapp/**
          if-no-files-found: error

      - name: Publish
        run: dotnet publish "${{github.workspace}}/my-web-app/my-web-app.csproj" -c Release -o mywebapp
          
      - name: Dump GitHub context2
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

